ALTER TABLE order_detail
    ADD shipped_from_id INT;

ALTER TABLE order_detail
    ADD CONSTRAINT FK_ORDER_DETAIL_ON_SHIPPEDFROM FOREIGN KEY (shipped_from_id) REFERENCES location (id);

ALTER TABLE ORDER_LOCATIONS
    DROP CONSTRAINT FK_ORDLOC_ON_LOCATION;

ALTER TABLE ORDER_LOCATIONS
    DROP CONSTRAINT FK_ORDLOC_ON_ORDER;

DROP TABLE ORDER_LOCATIONS CASCADE;